### PR TITLE
.NET Standard

### LINKED ISSUE #65: .NET Core support
Hello,

it would be great to support .NET Core. Right now it fails saying that the type Attribute is defined in an unreferenced 'mscorlib' assembly.

### LINKED ISSUE #69: .NET Standard support
Hey guys,

.NET Standard is the future -- would be nice to support this so I can switch from using PCLs (many other packages I use are adding support, this is one of the only ones that doesn't support it).

Thanks!

### PR DESCRIPTION
**Pull request by tpluscode**
Fixes #65
Fixes #69

* [x] moved projects to new csproj
* [x] moved tests to Xunit (NUnit still doesn't work with the new proj format)
* [x] updated appveyor.yml to build with new .NET tooling
* [x] fix `dotnet build`
    I don't understand why the solution builds fine in VS2017 but fails from commandline
* [ ] fix `ApprovedTests`
* [ ] fix `LargeAssemblyTest`

### CODE REVIEW

**Comment by distantcam** [comment]
Why are you moving all the projects over to .NET Standard? Why not just create another assembly to process that's .NET Standard, and then make sure the weaver works with that assembly?

**Comment by tpluscode** [comment]
With test new csproj format it's easier to build multiple targets. Otherwise it's a mess of keeping csprojs for each target in sync. Although I agree that the benefits may be less so in a relatively small solution...

**Comment by tpluscode** [comment]
Would you like me to try another PR with the approach you propose. Given that I've hit unexpected roadblocks, it could indeed be a better choice for the time being

**Comment by distantcam** [comment]
I suspect it would be easier.

**Comment by SimonCropp** [comment]
chose the other one

**Pull request closed without merging**
