### PR TITLE
Handle modreq/modopt

### LINKED ISSUE #598: NullGuard generates invalid IL with records when init is used
### Problem

When run with NullGuard the record below named `FooRecordWithInit` returns a `System.InvalidProgramException: 'Common Language Runtime detected an invalid program.'` .
With the setup for NullGuard `Mode="NullableReferenceTypes"` and `IncludeDebugAssert="false"/>`.

```csharp
public record FooRecordWithInit
{
    private int _id;
    public int Id
    {
        init => _id = value;  //< ERROR: Common Language Runtime detected an invalid program.
    }
}
```
The underlying issue seems to be the invalid IL weaved by Fody as seen here:
```csharp
public int Id
{
  init
  {
    _id = value;
    if ((int)/*Error near IL_0007: Stack underflow*/ == 0)
    {
    throw new InvalidOperationException("[NullGuard] Return value of method 'System.Void modreq(System.Runtime.CompilerServices.IsExternalInit) Bug.FooRecordWithInit::set_Id(System.Int32)' is null.");
    }
  }
}
```
In other situations a record works fine with a setter instead of init:
```csharp
public record FooRecordWithSet
{
    private int _id;

    public int Id
    {
        set => _id = value; //< Works
    }
}
```
### Reproduce the issue
A minimal Solution to reproduce the issue can be found [here](https://github.com/sinantutan/nullguard-fody-records-init-bug).

1. Clone the repository.
2. Build the project.
3. Use [ILSpy](https://marketplace.visualstudio.com/items?itemName=SharpDevelopTeam.ILSpy) to view the output. 

### Configuration

Operating System: Windows 11 Enterprise 64-Bit (10.0, Build 22621)
Framework Version: .NET 6 
Packages: Fody 6.6.4, NullGuard.Fody 3.1.0
x64

### PR DESCRIPTION
**Pull request by ltrzesniewski**
Fixes #598

Tests seem to be broken on master, so I can't really test if there's no regression, but I don't have time to clean up the project right now. I'm still submitting this PR as I think it should do the job. Feel free to take this over if you'd like.

### CODE REVIEW

**Comment by SimonCropp** [comment]
i will take a look at the master build

**Comment by tom-englert** [comment]
I finished and merged #594 to fix the existing tests.
I moved the tests you added to the NRT specific test set, because simply adding a record introduces NRT annotations, so auto-detection changes the `NullGuardMode` from `Implicit` to `NullableReferenceTypes`, breaking half of the tests.

**Comment by ltrzesniewski** [comment]
> because simply adding a record introduces NRT annotations

Ooooh I see, I wasn't aware of that, and didn't undersatand what was going on. Thanks!

**Comment by tom-englert** [comment]
Yes, I was surprised too, how such a marginal change can break so many tests

**Comment by tom-englert** [comment]
@ltrzesniewski to me that looks OK

**Comment by ltrzesniewski** [comment]
Ok, I wanted to take a look at the stack underflow aspect, but I suppose this can be handled independenly of this PR as well.

**Pull request merged**
