### PR TITLE
[WIP] Injection of JetBrains Annotations

### PR DESCRIPTION
**Pull request by ulrichb**
Implements feature request #54.

During implementing this PR, I mentioned that the [proposed option 2](https://github.com/Fody/NullGuard/issues/54#issuecomment-134158391) is a problem for rewritten libraries which already reference `JetBrains.Annotations` and use `ILMerge /internalize`. If _NullGuard_ would inject internal `NotNullAttribute` declarations, `ILMerge` would fail because of duplicated type declarations (respectively the `/allowDup` switch would rewrite the type names which would be ignored by R#).

Therefore I implemented option 1 (with a new `[InjectJetBrainsAnnotations]` configuration attribute). It's named "JetBrainsAnnotations" because the injected attributes are JetBrains.Annotations/ReSharper-specific in the following ways.
1. For method results, decorating the _method itself_ with `[NotNull]` instead of the return type.
2. Decorating `[ItemNotNull]` on `async` methods instead of `[NotNull]` (see [RSRP-376091](https://youtrack.jetbrains.com/issue/RSRP-376091#id_l.I.ic.it.c.c_27_1054764.comment_content_row_27_1054764)).
3. Decorating `[NotNull]` only for the whole property (ReSharper doesn't support `[return: NotNull]` or `[param: NotNull]` for property getters/setters).

@reviewers:
- It's probably easier to review the two commits separately because the first one has a lot of changes but only restores the removed custom attribute assertions in the tests, lost in commit 5f6673d1bc7d974ff9efb45dfee17d1b9a77a74d.
- I have two review questions (see REVIEW comments in `ModuleWeaver.cs` and `AssemblyWeaver.cs`).

### CODE REVIEW

**Comment by Felorati** [comment]
This would be such a great feature, enable both static and runtime analysis using the jetbrains annotaion. Did this get stuck?

**Comment by matkoch** [comment]
@distantcam could you please merge this?

**Comment by matkoch** [comment]
ping @SimonCropp

**Comment by tom-englert** [comment]
@ulrichb @matkoch @Felorati 
Now that NullGuard is going to support the [NotNull] attribute of R# (s. #88), doe this PR still make sense to anyone?

**Pull request closed without merging**
